table 'Product Subcategories Lookup'
	lineageTag: fac4a888-8e99-482d-a664-bbf6c6b5afe3

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: b8e3f653-2ba6-4818-b74a-71051762e57b
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 13a00f30-d915-4c92-a68d-22343066781d
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 47adbf82-1c0f-42a4-9bdb-dccb2a494187
		summarizeBy: count
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\adventure_works\Adventure Works Raw Data\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, QuoteStyle=QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

