table 'Product Categories Lookup'
	lineageTag: bd24e427-0af7-4265-9a5c-999cda8fd501

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 5a2ff199-2b91-4e39-920d-2bc5b24f1466
		summarizeBy: count
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 5d1fc88b-f380-4288-a5fc-7be7e761761b
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup' = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\adventure_works\Section 3 - Connecting & Shaping Data\Adventure Works Raw Data\AdventureWorks Product Categories Lookup.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

